= DADL Data Description Language 
OPS4J 
:doctype: book 
:toc: left 
:toclevels: 3
:toc-position: left 
:toc-title: OPS4J DADL 
:numbered:

// Push titles down one level
:leveloffset: 1

++++ 
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/3.1.0/css/font-awesome.min.css">
++++

:icons: font

= Introduction

== Purpose

DADL is a language for describing data formats, accompanied by a tool for parsing and generating 
data in a given format described by a DADL model.

Unlike most data modelling languages, DADL not only defines a logical content model, but also
a precise representation of data as a binary stream. In fact, the main purpose of DADL is
to formalize existing data formats that are loosely specified by examples, tabular descriptions
or technical prose. 

A DADL model is written in XML according to a given schema. Thus, no special tools are required
to edit a DADL model.

The DADL code generator generates types of a target language, logically corresponding to the 
data types defined in a DADL model.

The DADL runtime parses a DADL model and provides marshallers and unmarshallers for binary streams
satisfying this model. A marshaller takes a target programming language object graph and serializes 
it to a binary stream. Conversely, an unmarshaller deserializes a binary stream into a target 
language object graph.

== Java as target language

While the DADL language is nothing but XML and does not depend on any given target language, the
DADL reference implementation is focused on Java and relies heavily on established Java 
specifications like JAXB and EL. 

DADL comes with a Maven plugin to generate Java target classes from a DADL model during the
build process. The generated model only contains simple beans and enums. The marshalling 
and unmarshalling logic is not contained in the generated code, but in a DADL runtime library which
does not depend on any given model.

== Motivation

The driving force behind DADL is the need to decode and generate some specific proprietary data
formats that have no formal specifications. Hence, the main requirement for DADL is to retrofit
a formal specification onto an existing data format. The secondary requirements are Java, Open
Source and ease of use.

Data modelling languages can be categorized as prescriptive or descriptive. A *prescriptive* language
starts with a logical data model and defines one or more encoding schemes, with the exact encoding
format being irrelevant as long as the intended information can be decoded.

A *descriptive* language starts with a physical data format and maps this format to a logical
model with encoding rules such that the encoded structures exactly match the original format.

Most of the better-known data modelling languages and frameworks like 
http://www.w3.org/TR/2006/REC-xml11-20060816/[XML], 
http://json.org/[JSON], ASN.1 <<asn1>>, 
https://developers.google.com/protocol-buffers[Protocol Buffers] or 
https://thrift.apache.org/[Thrift] are prescriptive and thus do not match our requirements.

There are some lesser-known prescriptive languages like ASN.1 ECN <<ecn>>, 
FAN.1 <<fan1>>, 
http://csn1.info[CSN.1], 
http://people.cs.vt.edu/~gback/papers/gback-datascript-gpce2002.pdf[DataScript] and 
https://www.ogf.org/documents/GFD.207.pdf[DFDL]
that were considered as alternatives. Among these, only DFDL turns out to be a close match, 
supporting both binary and textual formats.

Currently (August 2015), 
https://opensource.ncsa.illinois.edu/confluence/display/DFDL/Daffodil%3A+Open+Source+DFDL[Daffodil] 
is the only Open Source implementation of DFDL. It provides
a Java API, but is implemented in Scala, which does not match our secondary requirements and 
rules out the option of contributing to Daffodil or creating a fork to make it fit our requirements. 

Moreover, a quick test revealed that some DFDL features required for our data formats are not yet 
implemented in Daffodil. For some special constructs in these data formats, it is yet unclear if 
and how they can be expressed in DFDL at all.

For this reason, the DADL project was created to come up with a pragmatic solution, building
upon concepts defined in DFDL, but not with the goal to implement the DFDL specification. While DADL
does reuse quite a few definitions from DFDL (including most representation properties), it takes
a different route in some central aspects, like using a custom XML schema instead of annotated
XSD or Java Expression Language instead of XPath.

DADL is a means to an end, not a goal in itself. New features will be added to DADL only when
driven by the specific needs of a specific data format of interest to DADL contributors. 


= Working with DADL

Applications that need to produce or consume a non-standard data format can use DADL to 
simplify this task. This requires the following steps:

* Create a DADL model of your data format in XML. The model must satisfy the
DADL XML schema `dadl-metamodel.xsd` which is contained in the `dadl-metamodel` artifact.

* Generate a Java model from the DADL model, either programmatically, or using the 
`dadl-maven-plugin`.

* In your application, to produce data in the target format, build a Java object graph using the 
generated Java model  classes, load the DADL XML model into a `DadlContext` and create a 
`Marshaller` to serialize the root of the object graph into a `BitStreamWriter`.

* Similarly, to consume data in the target format, load the DADL XML model into
a `DadlContext` and create an `Unmarshaller` to deserialize data from a `BitStreamReader` into a
Java object graph.

= Concepts

== Types and content types

DADL is used to model data types. A *type* is either a simple type or a complex type. A *complex 
type* is composed of *elements* of other types, simple or complex. A *simple type* cannot be 
decomposed further.

A DADL *model* is a set of types.

In a given DADL model, each type has a unique name, a content type and a representation. 
Roughly speaking, the content type defines what a type _is_, and the representation defines 
what it _looks like_.

The content type of a simple type is one of `integer`, `text` or `opaque`. The values of integer
types are whole numbers, positive, negative or zero. The values of text types are strings of Unicode
characters, where Unicode just defines the set of available characters, and not their encoding. The
encoding is defined by the representation of a DADL type. An opaque type is just a container that
cannot be interpreted in the context of the given model.

For example, consider a simple type `Age` with content type `integer` and representation _16-bit
unsigned integer, big-endian_. Alternatively, the representation might be _5-digit decimal ASCII
string_.

== Values and bit stream representations

A type can be regarded as a set of its possible *values*. In a given DADL model, each value has
a _unique_ representation as a *bit stream*. A bit stream is a finite sequence of *bits*, where
each bit is either zero or one. The size or length of a bit stream is the number of bits in the
sequence. The bits of a bit stream of length n are numbered from 0 to n-1.
Bit 0 comes first, bit n-1 comes last. This number is also called *bit position*.

The values of an opaque content type are just bit streams, which amounts to saying that an opaque
value does not possess any semantic interpretation.

A *byte stream* is a special case of a bit stream with length divisible by 8. Thus, the sequence
of bits can be split into subsequences of 8 bits. Each such subsequence is called a *byte* or 
*octet*. The length of a byte stream is the number of bytes, equal to the number of bits divided
by 8. The bytes of a byte stream of length n are numbered from 0 to n-1. This number is also
called *byte position*. The bits of the byte at position k have positions 8k, 8k+1, ..., 8k+7 in the
underlying bit stream.

== Representation properties

The concrete representation of a DADL type is defined by a number of *representation properties*.
A type may reference another base type. In this case, any property not explicitly redefined on the 
referencing type is inherited from the base type. 

== Length

The length of a type (or more precisely, the length of each of its value representations) 
is determined by the properties `lengthKind`, `lengthUnit`, `length` and `minLength`.

The length is measured in a `lengthUnit` of `bit`, `byte` or `char`. Character length `char` only
applies to text types.

Types with a `minLength` property will be padded to this length when their actual length is shorter
than the `minLength` value.

The `lengthKind` is either `explicit` or `implicit`. An explicit length is defined by the `length`
property on the given type. Simple types have explicit length. Complex types may have implicit
length, which means that the length of the complex value is defined by the total length of its
elements, including tags and length fields.          

== Simple types

Each simple type has a `contentType` property with a value of `integer`, `text` or `opaque`.
Additional properties for each content type are defined in the following sections.

The `mappedType` property defines the type to be used in the target language model.

For special cases that cannot be captured by the default mapping rules, a DADL model may 
specify named type adapters using the `adapter` property. Applications working with the DADL
runtime shall register an adapter implementation with the corresponding name for each adapter name
occurring in the loaded model. An adapter implements a custom marshalling and unmarshalling 
strategy for a given type. 

=== Integer types

Integer types can be represented as binary or as text. For Java, the `mappedType` must be one of 
`byte`, `short`, `int`, `long`, `Byte`, `Short`, `Integer`, `Long` or `BigInteger`.

Binary representation has two variants defined by the `binaryNumberRepresentation` property
with values of `binary` or `bcd`. 

`binary` representation is the usual two's complement number representation, further determined by 
the values of the `byteOrder` and `bitOrder` properties.

For example, the decimal number 261 can be written as 2⁸ + 2² + 2⁰, so its binary representation is
`0000 0001 0000 0101`. This corresponds to the default bit stream representation with `byteOrder =
bigEndian` and `bitOrder = mostSignificantBitFirst`.

`littleEndian` reverses the order of bytes in the byte stream, and `leastSignificantFirst` reverses
the order of bits within a byte.

So the four possible combinations of byte order and bit order result in the following representations:

|===
|*byte order*   |*bit order*                |*representation*
|`bigEndian`    |`mostSignificantBitFirst`  |`0000 0001 0000 0101`
|`bigEndian`    |`leastSignificantBitFirst` |`1000 0000 1010 0000`
|`littleEndian` |`mostSignificantBitFirst`  |`0000 0101 0000 0001` 
|`littleEndian` |`leastSignificantBitFirst` |`1010 0000 1000 0000` 
|===

In `bcd` representation, numbers are represented as binary coded decimals, where each decimal
digit is encoded by its 4-bit binary representation, from `0000` to `1001` (i.e. zero to nine). 
`bcd` representations are byte-aligned. For values with an odd number of digits, the most 
significant bits of the most significant byte are filled with zero.

In textual representation, numbers are written in the standard decimal representation in the 
character encoding specified by the `encoding` property. In this case, the `lengthUnit` must be 
`char`, indicating the number of decimal digits for the number representation
(also counting sign and separators, if required).

If the `length` value is greater than the number of characters required by the decimal
representation, then the number representation will be padded with the value of the 
`textNumberPadCharacter` property, usually zero or a blank space. The `textNumberJustification`
property with possible values of `left`, `right`, `center` indicates whether the pad character
will be added on the right, on the left or equally on both sides. For `center` justification,
one extra character may be added on the left side if needed. 

=== Text types

Text values are represented in the character encoding defined by the `encoding` property. 
The `mappedType` must be `String`. 

The `textPadKind` property with value `none` or `padChar` defines whether or not the text is padded.

When `textPadKind` is `none`, it is an error if the actual encoded length does not equal the 
length specified by the `lengthUnit` and `length` properties.

When `textPadKind` is `padChar`, the text will be padded, if required, by the value of the 
`textStringPadCharacter` property, using left, right or center justification as indicated by the 
value of the `textStringJustification` property, similar to the `textNumberJustification`
defined above.

=== Opaque types

Values of opaque types are copied verbatim between the representation and the target language 
model. The mapped type must be `byte[]`.

=== Enumerations

An enumeration type is a restriction of a given simple type to a finite number of elements. Each
element has a name and a value. The name is defined by the `name` property. The value is defined
by exactly one of the `value`, `decValue` or `hexValue` properties, defining a string value,
a decimal number value or a hexadecimal number value, respectively.

== Complex types

A complex type is either a sequence, a tagged sequence or a choice.

=== Sequence 

A *sequence* has zero or more elements, each with a name and a type. The order of the elements
is significant. The content type of a sequence type is the Cartesian product of the content types
of the element types in the given order.

A sequence value is a tuple of element values. The representation of the sequence value is the
concatenation of the representations of the element values in the given order.

By default, each sequence element occurs exactly once. Sequence elements can specify a minimum
or maximum number of occurrences with the `minOccurs` and `maxOccurs` properties. The actual 
number of occurrences can be specified using the `occursCountKind` and `occursCount` properties.
The `occursCountKind` is either `expression` or `parsed`. 

In the `expression` case, the `occursCountKind` property must be set to an expression indicating
the actual number of occurrences.

In the `parsed` case, the actual number of occurrences is determined by speculative parsing, with
the parser backtracking to the end of the last occurence after a parse error, continuing with the
next element of the enclosing sequence.

=== Tagged Sequence

A *tagged sequence* is a sequence preceded by a tag and a length field. The tag has an integer
type and a fixed value. The length field has an integer type. The value of this type is the total 
byte length of the elements of the tagged sequence, by default not counting the tag and the length 
field itself.

The representation of a tagged sequence is the concatenation of the tag value representation, the 
length field value representation and the element value representations in the given order.

=== Choice

A *choice* has one or more elements, each with a name and a type. The order of the elements is
significant. The content type of a choice is the union of the content types of the element types.

A choice value is a value of exactly one of the element types. The representation of the choice
value is just the representation of the given element value.
 
== Expressions

Some representation properties that logically take a numeric value can actually take a string
expression in 
https://jcp.org/aboutJava/communityprocess/final/jsr341/index.html[Expression Language 3.0]. 
The expression must evaluate to an integer value. DADL automatically sets a number of variables 
to support cross-references between field of the current type.

The `self` variable refers to the current element. If this element is a complex type, `self.foo`
refers to the bean property `foo` of the corresponding mapped type (i.e. the Java bean class 
corresponding to the complex DADL type).

The `up` list variable refers to the hierarchy of objects containing the current element. `up[0]`
is equal to `self`. 

`up[1]` is the complex type instance containing the current element. `up[2]`
is the complex type instance (if applicable) containing `up[1]` and so on.

Using the `outputValueCalc` property with an EL expression, the model can define a calculated or 
even fixed value for a simple type.

Expressions can also be used for `length` or `occursCount` properties.
 

= References
[bibliography]
- [[[asn1]]] ISO 8824-1 | ITU-T X.680: _Abstract Syntax Notation One (ASN.1): 
  Specification of basic notation_.
- [[[ecn]]] ISO 8825-3 | ITU-T X.692: _ASN.1 encoding rules: 
Specification of Encoding Control Notation (ECN)_. 
- [[[fan1]]] W. Gora, H. Körzdörfer: _Ein universeller Datenmonitor zur Netzdiagnose und 
  Leistungsbewertung_. In: U. Herzog, M. Paterok (ed.): _Messung, Modellierung und Bewertung
  von Rechnersystemen_, Springer-Verlag, 1987.

// Return to normal title levels 
:leveloffset: 0
